### ISSUE TITLE
Update Awario documentation

### ISSUE THREAD

**Issue by Trudko** [blockstack/docs.blockstack#468]
I was going through [Awario app reviewer section](https://docs.blockstack.org/develop/app-reviewers.html#awario) to get up to date with latest changes and I've found some important information to be missing.

IMHO reach score could be explained more clearly, what exactly does it mean and what should app miners to do increase it. Also it would be helpful to mentioned examples from it like meetup.com and medium.com

I would mention 1000 points limit for eligibility of Growth score too. I've found about it through checking app mining results more closely.

**Comment by cuevasm** [comment]
Thanks Trudko, the docs aren't really the place where we put recommendations to Miners. As we have time and bandwidth, we add those to the App Miner Guide (available on the menu to the left of the docs you're reviewing here). Medium is actually mentioned in the docs already and I can certainly add something about the Growth score, it was very uncommon for that to play a role in scoring before we switched to Blended Awareness in the last couple months so that's why you don't see it there. 

Generally speaking, upping one's Reach is simply a matter of getting Mentions in media publications or the (News/Blog category in Awario as explained in the Awario scoring section). There are numerous ways to accomplish this, if I have time over the holidays I can look to put my own recommendations together, but nothing will be definitive or right for every app.

**Comment by moxiegirl** [comment]
@cuevasm @Trudko I'm going to close this for now. Feel free to re-open if you think I am closing it in error or something new develops.

**Comment by cuevasm** [comment]
I just shared a document with you that can be added to the App Miner Guide for Awario when you have time, thanks!
