### ISSUE TITLE
Sidecar and Core API documentation

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs.blockstack#580]
With Stacks 2.0, we have to rethink how we document the node APIs. 

Right now, we simply link to the "Stacks Node API": https://core.blockstack.org/. The refs include mostly `v1` endpoints. 

## Issue 
With the addition of Stacks 2.0 and the Sidecar, we now have `v1` and `v2` core endpoints in addition to sidecar endpoints. It is unclear what the documentation should link to and how it should introduce the APIs.

## Proposal
In order to make it easier for developers to understand what to use, we propose to point them to the Sidecar APIs:
- Add a "Stacks Blockchain API" intro page that briefly explains the functionality provided and how it fits together architecturally. It would link to the core API ref (https://core.blockstack.org/) and describe that it is a wrapper, proxying to some core API endpoints.
- Replace the "Stacks Node API" reference link in the nav with a "Stacks Blockchain API" ref (https://blockstack.github.io/stacks-blockchain-sidecar/)
- Replace all links to "Stacks Node API" in the docs with links to https://blockstack.github.io/stacks-blockchain-sidecar/

## Questions
- @kantai: Will the core node `v1` endpoints continue to exists? Will the new `v2` core endpoints be documented in https://core.blockstack.org/?
- @kantai: Are we OK mainly pointing devs to the sidecar project as opposed to the core node API? Implications?
- @zone117x: Are we OK for the sidecar API documentation to be the "source of truth"? Implications?

**Comment by hstove** [comment]
Noting that we already have v2 node RPC docs here: https://docs.blockstack.org/core/smart/rpc-api.html

I would personally recommend holding off on committing to new properties (like at blockstack.github.io) until we have our new docs engineer on the team. There is no good reason these things can't all live in the same place.

**Comment by agraebe** [comment]
ah, now we have v1 docs, v2 docs and sidecar docs it seems. I don't think there's a need for all 3. 

Considering all of the complexity and the lack of urgency, should we put this on the back burner until the new docs eng joins @kyranjamie?

**Comment by kantai** [comment]
> @kantai: Will the core node v1 endpoints continue to exists? Will the new v2 core endpoints be documented in https://core.blockstack.org/?

We are going to try to ensure some backwards compatibility with v1 endpoints. We don't have any plans currently to document specifically at core.blockstack.org, and I'd be open to hosting the API documentation basically anywhere.

> @kantai: Are we OK mainly pointing devs to the sidecar project as opposed to the core node API? Implications?

Fine by me -- however, I don't think this removes the need for the core node API to be documented in the core node's repo. For anyone that's consuming the core node API (including the side car, but also things like transaction libraries), they're going to need the API spec. The "source of truth" for that spec should be the stacks-blockchain repository. Otherwise, it'll be very difficult to insure that PRs on the stacks-blockchain repository include the requisite documentation updates. See for example: https://github.com/blockstack/stacks-blockchain/pull/1510 -- this PR changes an HTTP interface, and includes the updates in the stacks-blockchain documentation. A process where that PR would need to be implemented and reviewed across multiple repositories, is, I think, untenable.

**Comment by kyranjamie** [comment]
The objective of this proposal is to reduce fiction for developers, and work for us.

With the introduction of the sidecar, we now have documentation in both the link @hstove shared, and [the generated docs in the sidecar](https://blockstack.github.io/stacks-blockchain-sidecar/), updated today with the core node endpoints.

How common of a use case will be it for blockstack developers to need to access both the sidecar and the core node RPC? One example, @zone117x provided, was library developers not wanting to trust another web server. Are there many any other cases, where the proxy won't suffice?
If not, it's a big win to point devs straight to a single API and docs, than two.
